name: Backpack
author: skjsjhb
description: Extra inventory for players.
website: https://bpd.skjsjhb.moe/docs/the-tutorial/backpack/sketch
main: Main
version: 1.0
api-version: 1.21

commands:
  backpack:
    aliases:
      - bp
    usage: /backpack
    description: Opens backpack.