name: BayonetCharge
author: skjsjhb
description: Charge and dash with an iron sword on your hand!
website: https://bpd.skjsjhb.moe/docs/the-tutorial/bayonet-charge/sketch
main: Main
version: 1.0
api-version: 1.21